[tool.poetry]
name = "support"
version = "0.1.0"
description = ""
authors = ["AJ <Ajay.Koenig@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
matplotlib = "^3.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
