#ifndef SOFTWARE_CERT_H
#define SOFTWARE_CERT_H

#include "Arduino.h"
// cert string
String cert = "-----BEGIN CERTIFICATE-----\n"
    "MIIDWTCCAkGgAwIBAgIUMbn0kVe2lRBkgoQ3joYgyenyHpswDQYJKoZIhvcNAQEL\n"
    "BQAwPDELMAkGA1UEBhMCQ04xHDAaBgNVBAoME1Jlc2VhcmNoIGFuZCBEZXNpcmUx\n"
    "DzANBgNVBAMMBlJBRCBDQTAeFw0yNDA1MTIwNDQ2MzBaFw0yNTA1MTIwNDQ2MzBa\n"
    "MDwxCzAJBgNVBAYTAkNOMRwwGgYDVQQKDBNSZXNlYXJjaCBhbmQgRGVzaXJlMQ8w\n"
    "DQYDVQQDDAZSQUQgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCq\n"
    "PK2gCByqXc8vLJrScU4ELQj1r0vXDogpXbJ5qI7l13KVsZDMJiCseMXbf5WihMdt\n"
    "gQkRzdCdVyr9G7TfH8PepKHT6PnI2NDdg5zVDGU6nIzjdXRnIdD+3T9X/CKKHPJQ\n"
    "A9owEt+kW9qd3BLwGPSlfvuD1aF5X31YEn/w7hDQD2EWPwzHoJ/USgr12uzwc1bs\n"
    "nJJdctg2WlpGVuOT1VPZD7HFuCQf/C0q/9Huog33gSwLRksGzLz00kyGYuIUcg8m\n"
    "k0vKPPNaySrZo+JNgGnfvE/x5BekdNOttDGU03s8Eiv9bKJNigD+1K0dyf7lcnM6\n"
    "3vrkfIVtXTurdW4A+pUDAgMBAAGjUzBRMB0GA1UdDgQWBBQHReM0tH9S/3t/5DDa\n"
    "ZeZJgBE2FDAfBgNVHSMEGDAWgBQHReM0tH9S/3t/5DDaZeZJgBE2FDAPBgNVHRMB\n"
    "Af8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQB72VkSubC5MxXwwgokrjBcfpjY\n"
    "b0eLDkDxQq+rzdumdDQf4QyDgEBC/AbXuneHqvUdwSvQbQ2j0vM2khanDJgAD5C0\n"
    "83m4KblZ16GzzO9NXKPe4Hhf6M4J2/3m/fkgyJzCIEe14RJwuppbLKkiuCZf8dMT\n"
    "o3rqXxGcIf+us/aOLEkoE/VYuID/dC9E0owspcE+FzgfNtdfjH9QE3kJWe/iVGE1\n"
    "6PoUtSsHTA5z9BaFbMG1nBGSvtzpTWLMBvMAPtPyXA0iRvF1Z3tZT94UG3mNbidT\n"
    "4xwRWVDg5J5+gAM+7nlYjdAmrZinvc3OCuFRady+VvtmNPb9Xl5atdacuLdv\n"
    "-----END CERTIFICATE-----";

#endif  // SOFTWARE_CERT_H
