// Generated by scripts/generate_streaming_stress_header.py. Do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace streaming_stress {
inline constexpr uint32_t kDurationMs = 15000;
inline constexpr uint32_t kSettlingMs = 5000;
inline constexpr uint32_t kAlignmentGuardMs = 750;
inline constexpr uint32_t kSamplePeriodMs = 4;
inline constexpr uint32_t kMaximumLagMs = 750;
inline constexpr uint32_t kRandomSeed = 20260719u;

inline constexpr Profile kProfiles[] = {
    {"nominal", 25, 75, 500, 20, 40, 50, 60, 50, 50, true},
    {"gentle", 40, 60, 250, 10, 20, 30, 40, 20, 0, true},
    {"large_slow", 10, 90, 250, 20, 45, 70, 80, 50, 50, true},
    {"near_limit", 20, 80, 1000, 25, 85, 70, 80, 90, 50, true},
    {"soft_offset", 25, 75, 350, 20, 55, 30, 85, 15, 50, true},
    {"compensation_off", 25, 75, 500, 20, 40, 50, 60, 50, 50, false},
    {"zero_buffer", 25, 75, 500, 20, 40, 50, 60, 50, 0, true},
    {"maximum_buffer", 25, 75, 500, 20, 40, 50, 60, 50, 100, true},
};
inline constexpr size_t kProfileCount = sizeof(kProfiles) / sizeof(kProfiles[0]);

inline constexpr FaultCase kFaults[] = {
    {"sine_jitter", Pattern::Sine, Delivery::Jitter, 0, 6101u},
    {"sine_gaps", Pattern::Sine, Delivery::Gaps, 0, 6102u},
    {"triangle_bursts", Pattern::Triangle, Delivery::Bursts, 0, 6103u},
    {"triangle_cadence_pressure", Pattern::Triangle, Delivery::CadencePressure, 3, 6104u},
    {"random_irregular_durations", Pattern::Random, Delivery::Irregular, 0, 6105u},
    {"random_micro_macro", Pattern::Random, Delivery::MicroMacro, 3, 6106u},
};
inline constexpr size_t kFaultCount = sizeof(kFaults) / sizeof(kFaults[0]);
inline constexpr size_t kPatternCount = 3;
inline constexpr size_t kCoreCaseCount = kPatternCount * kProfileCount;
inline constexpr size_t kRepeatCount = kPatternCount;
inline constexpr size_t kCaseCount = kCoreCaseCount + kFaultCount + kRepeatCount;
}
