#!/usr/bin/env python3
"""Generate the compact C++ catalog used by on-device streaming tests."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "test" / "streaming_stress_suite.json"
DEFAULT_OUTPUT = ROOT / "lib" / "OSSMLogic" / "src" / "streaming_stress_suite.generated.h"


def enum_name(value: str) -> str:
    return "".join(part.capitalize() for part in value.split("_"))


def render(document: dict) -> str:
    profiles = document["profiles"]
    profile_indexes = {profile["id"]: index for index, profile in enumerate(profiles)}
    lines = [
        "// Generated by scripts/generate_streaming_stress_header.py. Do not edit.",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace streaming_stress {",
        f"inline constexpr uint32_t kDurationMs = {document['durationMs']};",
        f"inline constexpr uint32_t kSettlingMs = {document['settlingMs']};",
        f"inline constexpr uint32_t kAlignmentGuardMs = {document['alignmentGuardMs']};",
        f"inline constexpr uint32_t kSamplePeriodMs = {document['samplePeriodMs']};",
        f"inline constexpr uint32_t kMaximumLagMs = {document['maximumLagMs']};",
        f"inline constexpr uint32_t kRandomSeed = {document['randomSeed']}u;",
        "",
        "inline constexpr Profile kProfiles[] = {",
    ]
    for item in profiles:
        lines.append(
            '    {"%s", %d, %d, %d, %d, %d, %d, %d, %d, %d, %s},'
            % (
                item["id"], item["minimum"], item["maximum"],
                item["frequencyMilliHz"], item["cadenceHz"], item["speed"],
                item["stroke"], item["depth"], item["sensation"], item["buffer"],
                "true" if item["latencyCompensation"] else "false",
            )
        )
    lines += [
        "};",
        "inline constexpr size_t kProfileCount = sizeof(kProfiles) / sizeof(kProfiles[0]);",
        "",
        "inline constexpr FaultCase kFaults[] = {",
    ]
    for item in document["faults"]:
        lines.append(
            '    {"%s", Pattern::%s, Delivery::%s, %d, %du},'
            % (
                item["id"], enum_name(item["pattern"]), enum_name(item["delivery"]),
                profile_indexes[item["profile"]], item["seed"],
            )
        )
    lines += [
        "};",
        "inline constexpr size_t kFaultCount = sizeof(kFaults) / sizeof(kFaults[0]);",
        "inline constexpr size_t kPatternCount = 3;",
        "inline constexpr size_t kCoreCaseCount = kPatternCount * kProfileCount;",
        "inline constexpr size_t kRepeatCount = kPatternCount;",
        "inline constexpr size_t kCaseCount = kCoreCaseCount + kFaultCount + kRepeatCount;",
        "}",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render(json.loads(args.input.read_text()))
    if args.check:
        return 0 if args.output.is_file() and args.output.read_text() == rendered else 1
    args.output.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
