// Describes every board-level define that is available

#define WEBLOG_AVAILABLE 0

#define CANOPEN_AVAILABLE 0
#define CANOPEN_DEFAULT FUNCTIONALITY_ENABLED
#define CANOPEN_RX_PIN 0
#define CANOPEN_TX_PIN 0
#define CANOPEN_BAUD_RATE

#define MODBUS_AVAILABLE 0
#define MODBUS_DEFAULT FUNCTIONALITY_DISABLED
#define MODBUS_RX_PIN 0
#define MODBUS_TX_PIN 0
#define MODBUS_BAUD_RATE 57600
#define MODBUS_SERIAL SERIAL_8E1

#define VCP_AVAILABLE 0
#define VCP_DEFAULT FUNCTIONALITY_DISABLED
#define VCP_BUFFER_SIZE 1024
#define VCP_BAUD_RATE 38400
#define VCP_RX_PIN 0
#define VCP_TX_PIN 0
