#define COMPILE_CANOPEN 0
#define COMPILE_VCP 0
#define COMPILE_LVGL 0

#define COMPILE_MODBUS 1
#define ENABLE_MODBUS FUNCTIONALITY_DISABLED
#define MODBUS_RX_PIN 16
#define MODBUS_TX_PIN 17
#define MODBUS_BAUD_RATE 57600
#define MODBUS_SERIAL SERIAL_8E1
