// Web Log will be enabled after a re-factor
#define WEBLOG_AVAILABLE 0

#define CANOPEN_AVAILABLE 1
#define CANOPEN_DEFAULT FUNCTIONALITY_ENABLED
#define CANOPEN_RX_PIN
#define CANOPEN_TX_PIN 

#define LVGL_AVAILABLE 1
#define LVGLENABLE_BY_DEFAULT FUNCTIONALITY_ENABLED

#define MODBUS_AVAILABLE 1
#define MODBUS_DEFAULT FUNCTIONALITY_DISABLED

#define VCP_AVAILABLE 1
#define VCP_DEFAULT 1
#define VCP_BUFFER_SIZE 1024
#define VCP_BAUD_RATE 38400
#define VCP_RX_PIN 44
#define VCP_TX_PIN 43

#define LVGL_AVAILABLE 1