name: Update Docs on PR

on:
  pull_request:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Ensure we check out the HEAD of the PR so we can push back to it
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run docs discovery script
        run: |
          chmod +x ./scripts/find-docs.sh || true
          ./scripts/find-docs.sh

      - name: Commit and push changes if any
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected; committing and pushing to PR branch."
            git add -A
            git commit -m "chore(docs): auto-update via scripts/find-docs.sh [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
